PUT HTTP://localhost:5000/accounts/modify/242430720 HTTP/1.1
Content-Type: application/json

{
    "password": "encryptedpassword",
    "newName": "Erkki Enkryptoitu",
    "newPassword": "enkryptoitusalasana"
}